#pragma once
#include <ntddk.h>

#define SF_PROCESS_TERMINATE       0x0001
#define SF_PROCESS_CREATE_THREAD   0x0002
#define SF_PROCESS_VM_OPERATION    0x0008
#define SF_PROCESS_VM_WRITE        0x0020
#define SF_PROCESS_DUP_HANDLE      0x0040
#define SF_PROCESS_SUSPEND_RESUME  0x0800

NTKERNELAPI NTSTATUS PsLookupProcessByProcessId(HANDLE ProcessId, PEPROCESS *Process);

#define IOCTL_SF_PROTECT_CALLER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_SF_CLEAR_PROTECTION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
